name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  make_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate changelog
        run: |
          pip3 install gitchangelog
          CURRENT_TAG=$(git describe --tags --abbrev=0 HEAD)
          PREV_TAG=$(git describe --tags --abbrev=0 "${CURRENT_TAG}~1")
          gitchangelog ${PREV_TAG}..${CURRENT_TAG} > ${{ github.workspace }}-gitchangelog.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-gitchangelog.md
          draft: true
