name: Test

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: make init
      - run: make test
      - run: make docker
